name: CD

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3  
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6
      
    - name: Restore Nuget packages
      run: nuget restore Fritz.HomeAutomation.sln
    
    - name: Build the Solution
      run: msbuild Fritz.HomeAutomation.sln /p:Configuration=Release
     
    - name: Test
      run: dotnet test --verbosity normal
     
    - name: release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:  
        draft: false
        prerelease: false
        release_name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
      
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.2
      with:
        path: ./bin/Release
        recursive_exclusions: '*.nupkg'
    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release.zip
        asset_name: release.zip
        asset_content_type: application/zip
    
    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
